In [19]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier

### Датасет из заданной таблицы истинности

In [20]:
df1 = pd.DataFrame({'A': [0., 0., 0., 0., 1., 1., 1., 1.], 
                    'B': [0., 0., 1., 1., 0., 0., 1., 1.],
                    'C': [0., 1., 0., 1., 0., 1., 0., 1.],
                    'D': [1, 0, 1, 0, 1, 0, 1, 0]})

### Сгенерированный датасет со случайными величинами из заданных диапазонов (вариация для нуля в диапазое (0, 0.4), вариация единицы – (0.6, 1.2)

In [21]:
# дублирование заданной таблицы истинности 9 раз
df2 = pd.DataFrame({'A': [0., 0., 0., 0., 1., 1., 1., 1.] * 9, 
                    'B': [0., 0., 1., 1., 0., 0., 1., 1.] * 9,
                    'C': [0., 1., 0., 1., 0., 1., 0., 1.] * 9,
                    'D': [1, 0, 1, 0, 1, 0, 1, 0] * 9})

In [22]:
# замена нулей и единиц случайными числами из заданных диапазонов
cols = ['A','B','C']
df2[cols] = np.where(df2[cols].eq(0), np.random.uniform(0, 0.4, size=(len(df2), len(cols))), 
                                      np.random.uniform(0.6, 1.2, size=(len(df2), len(cols)))) 
df2

A         B         C  D
0   0.139919  0.302831  0.184517  1
1   0.011605  0.135465  1.193060  0
2   0.073243  0.818854  0.094982  1
3   0.284813  0.954648  0.940017  0
4   0.949683  0.295110  0.014393  1
..       ...       ...       ... ..
67  0.355637  1.058699  0.966537  0
68  1.052154  0.322510  0.318317  1
69  0.791613  0.003361  1.079063  0
70  1.130723  1.197419  0.375417  1
71  1.149820  0.617043  0.933565  0

[72 rows x 4 columns]

In [23]:
# получен датасет из 80 строк для обучения
df = pd.concat([df1, df2], ignore_index=True)
df

A         B         C  D
0   0.000000  0.000000  0.000000  1
1   0.000000  0.000000  1.000000  0
2   0.000000  1.000000  0.000000  1
3   0.000000  1.000000  1.000000  0
4   1.000000  0.000000  0.000000  1
..       ...       ...       ... ..
75  0.355637  1.058699  0.966537  0
76  1.052154  0.322510  0.318317  1
77  0.791613  0.003361  1.079063  0
78  1.130723  1.197419  0.375417  1
79  1.149820  0.617043  0.933565  0

[80 rows x 4 columns]

### Разделение данных

In [24]:
# координаты вектора
X=df.iloc[:, :-1]
# преобразование DataFrame в массив NumPy
X=X.to_numpy()
X[:15]

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 1.        ],
       [1.        , 1.        , 0.        ],
       [1.        , 1.        , 1.        ],
       [0.13991907, 0.30283084, 0.18451672],
       [0.01160533, 0.13546528, 1.19305969],
       [0.07324316, 0.81885427, 0.09498175],
       [0.28481266, 0.95464839, 0.9400172 ],
       [0.94968298, 0.29510999, 0.01439315],
       [1.08697955, 0.07781745, 0.67328821],
       [1.14792903, 0.9230927 , 0.27760755]])

In [25]:
# метка (label)
y=df.iloc[:,-1]
# преобразование DataFrame в массив NumPy
y=y.to_numpy()
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

### Обучение многослойного персептрона в Scikit-learn

In [26]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), 
                    random_state=1)
clf.fit(X, y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

### Результат

In [27]:
clf.predict([[1.13, 0.21, 0.09], 
             [0.93, 0.71, 0.19], 
             [1.12, 0.21, 0.79], 
             [1.03, 1.07, 1.19], 
             [0.81, 1.01, 0.19],
             [1.02, 0.11, 1.10],
             [0.01, 0.21, 1.27],
             [0.31, 0.27, 1.08],
             [0.07, 0.77, 0.16],
             [1.20, 0.14, 1.07]])

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 0])