In [ ]:
import numpy as np

In [ ]:
data = np.random.randn(5, 4) # исходный двухмерный массив (выборка с нормальным стандартным распределением)
data

array([[ 0.18690841,  1.6018296 ,  0.18874649, -0.13237342],
       [-0.8271466 , -0.05786792,  1.80411106, -0.06284444],
       [ 0.30918083, -0.35194786, -0.64168061, -0.57842455],
       [-0.61732766,  0.06326159, -0.96198777, -0.25573585],
       [-0.44544105, -0.21466774, -0.32679925,  0.15732642]])

## Класс Unar_Operations

In [ ]:
class Unar_Operations:
    @staticmethod
    def abs(A, *slice):    # абсолютное значение
        if np.any(slice) > 0:
            B = np.abs(A[slice[0]:slice[1], slice[2]:slice[3]])    # применение унарной операции к срезу из исходного массива
            A = np.zeros(A.shape)                                  # создание нулевого массива размером как исходный массив
            A[slice[0]:slice[1], slice[2]:slice[3]] = B            # замена части нулевого массива срезом из исходного массива, к которому применена унарная операция
        else:
            A = np.abs(A)                                          # применение унарной операции ко всему исходному массиву, если не задан срез      
        return A


    def fabs(A, *slice):    # абсолютное значение (для вещественных данных работает быстрее)
        if np.any(slice) > 0:
            B = np.fabs(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                  
            A[slice[0]:slice[1], slice[2]:slice[3]] = B            
        else:
            A = np.fabs(A)                                             
        return A


    def sqrt(A, *slice):    # квадратный корень
        if np.any(slice) > 0:
            B = np.sqrt(np.fabs(A[slice[0]:slice[1], slice[2]:slice[3]]))    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.sqrt(np.fabs(A))              
        return A


    def square(A, *slice):    # возведение в квадрат
        if np.any(slice) > 0:
            B = np.square(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.square(A)            
        return A


    def exp(A, *slice):    # экспонента
        if np.any(slice) > 0:
            B = np.exp(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.exp(A)              
        return A


    def log10(A, *slice):    # десятичный логарифм
        if np.any(slice) > 0:
            B = np.log10(np.fabs(A[slice[0]:slice[1], slice[2]:slice[3]]))    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.log10(np.fabs(A))              
        return A
        

    def sign(A, *slice):    # знак элемента: 1 (для положительных чисел), 0 (для нуля) или -1 (для отрицательных чисел)
        if np.any(slice) > 0:
            B = np.sign(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.sign(A)              
        return A
        

    def ceil(A, *slice):    # наименьшее целое число, не меньшее его
        if np.any(slice) > 0:
            B = np.ceil(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.ceil(A)              
        return A
        

    def floor(A, *slice):    # наибольшее целое число, не большее его
        if np.any(slice) > 0:
            B = np.floor(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.floor(A)              
        return A
        

    def rint(A, *slice):    # округление до ближайшего целого
        if np.any(slice) > 0:
            B = np.rint(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.rint(A)              
        return A
        

    def modf(A, *slice):    # дробные и целые части массива в виде отдельных массивов
        if np.any(slice) > 0:
            B = A[slice[0]:slice[1], slice[2]:slice[3]]    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B
            A = np.modf(A)     
        else:
            A = np.modf(A)              
        return A
        

    def isnan(A, *slice):    # булев массив, показывающий, какие значения являются NaN
        if np.any(slice) > 0:
            B = np.isnan(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.isnan(A)              
        return A
        

    def isfinite(A, *slice):    # булев массив, показывающий, какие элементы являются конечными (не inf и не NaN) 
        if np.any(slice) > 0:
            B = np.isfinite(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.isfinite(A)              
        return A
        

    def isinf(A, *slice):    # булев массив, показывающий, какие элементы являются бесконечными
        if np.any(slice) > 0:
            B = np.isinf(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.isinf(A)              
        return A
        

    def cos(A, *slice):    # косинус
        if np.any(slice) > 0:
            B = np.cos(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.cos(A)              
        return A
        

    def cosh(A, *slice):    # гиперболический косинус
        if np.any(slice) > 0:
            B = np.cosh(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.cosh(A)              
        return A
        

    def sin(A, *slice):    # синус
        if np.any(slice) > 0:
            B = np.sin(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.sin(A)              
        return A
                

    def sinh(A, *slice):    # гиперболический синус
        if np.any(slice) > 0:
            B = np.sinh(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.sinh(A)              
        return A
                

    def tan(A, *slice):    # тангенс
        if np.any(slice) > 0:
            B = np.tan(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.tan(A)              
        return A
                

    def tanh(A, *slice):    # гиперболический тангенс
        if np.any(slice) > 0:
            B = np.tanh(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.tanh(A)              
        return A
                

    def arccos(A, *slice):    # арккосинус
        if np.any(slice) > 0:
            B = np.arccos(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.arccos(A)              
        return A
                

    def arccosh(A, *slice):    # гиперболический арккосинус
        if np.any(slice) > 0:
            B = np.arccosh(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.arccosh(A)              
        return A
                

    def arcsin(A, *slice):    # арксинус
        if np.any(slice) > 0:
            B = np.arcsin(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.arcsin(A)              
        return A
                        

    def arcsinh(A, *slice):    # гиперболический арксинус
        if np.any(slice) > 0:
            B = np.arcsinh(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.arcsinh(A)              
        return A
                        

    def arctan(A, *slice):    # арктангенс
        if np.any(slice) > 0:
            B = np.arctan(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.arctan(A)              
        return A
                        

    def arctanh(A, *slice):    # гиперболический арктангенс
        if np.any(slice) > 0:
            B = np.arctanh(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.arctanh(A)              
        return A
                        

    def logical_not(A, *slice):    # значение истинности not х
        if np.any(slice) > 0:
            B = np.logical_not(A[slice[0]:slice[1], slice[2]:slice[3]])    
            A = np.zeros(A.shape)                                     
            A[slice[0]:slice[1], slice[2]:slice[3]] = B      
        else:
            A = np.logical_not(A)              
        return A


    def array_3d (A, num):  # преобразование исходного двухмерного массива в трехмерный, копированием двухмерного массива вдоль третьей оси
        A = np.repeat(A[np.newaxis, :, :], num, axis=0)
        return A

## Вывод результатов для исходного массива:

In [ ]:
Unar_Operations.abs(data, 1, 3, 0, 3)     # абсолютное значение при заданном срезе

array([[0.        , 0.        , 0.        , 0.        ],
       [0.8271466 , 0.05786792, 1.80411106, 0.        ],
       [0.30918083, 0.35194786, 0.64168061, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [ ]:
Unar_Operations.abs(data)     # абсолютное значение для целого массива

array([[0.18690841, 1.6018296 , 0.18874649, 0.13237342],
       [0.8271466 , 0.05786792, 1.80411106, 0.06284444],
       [0.30918083, 0.35194786, 0.64168061, 0.57842455],
       [0.61732766, 0.06326159, 0.96198777, 0.25573585],
       [0.44544105, 0.21466774, 0.32679925, 0.15732642]])

In [ ]:
Unar_Operations.log10(data, 1, 3, 0, 3)     # десятичный логарифм при заданном срезе

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.08241751, -1.23756212,  0.25626327,  0.        ],
       [-0.50978744, -0.45352167, -0.19268108,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [ ]:
Unar_Operations.log10(data)     # десятичный логарифм для целого массива

array([[-0.72837117,  0.20461631, -0.72412111, -0.8781992 ],
       [-0.08241751, -1.23756212,  0.25626327, -1.20173311],
       [-0.50978744, -0.45352167, -0.19268108, -0.23775328],
       [-0.20948426, -1.19885988, -0.01683045, -0.59220839],
       [-0.35120976, -0.66823322, -0.48571895, -0.80319835]])

In [ ]:
Unar_Operations.sign(data, 1, 3, 0, 3)     # знак элемента при заданном срезе

array([[ 0.,  0.,  0.,  0.],
       [-1., -1.,  1.,  0.],
       [ 1., -1., -1.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
Unar_Operations.sign(data)     # знак элемента для целого массива

array([[ 1.,  1.,  1., -1.],
       [-1., -1.,  1., -1.],
       [ 1., -1., -1., -1.],
       [-1.,  1., -1., -1.],
       [-1., -1., -1.,  1.]])

In [ ]:
Unar_Operations.cos(data, 1, 3, 0, 3)     # косинус при заданном срезе

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.67697862,  0.99832612, -0.23120371,  0.        ],
       [ 0.95258315,  0.93870301,  0.80109097,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [ ]:
Unar_Operations.cos(data)     # косинус для целого массива

array([[ 0.98258342, -0.03102829,  0.9822402 ,  0.99125142],
       [ 0.67697862,  0.99832612, -0.23120371,  0.99802594],
       [ 0.95258315,  0.93870301,  0.80109097,  0.83732499],
       [ 0.81542827,  0.99799965,  0.57189049,  0.96747742],
       [ 0.90242072,  0.97704723,  0.94707468,  0.98764971]])

In [ ]:
Unar_Operations.array_3d(data, 4)   # преобразование двухмерного массива в трехмерный массив

array([[[ 0.18690841,  1.6018296 ,  0.18874649, -0.13237342],
        [-0.8271466 , -0.05786792,  1.80411106, -0.06284444],
        [ 0.30918083, -0.35194786, -0.64168061, -0.57842455],
        [-0.61732766,  0.06326159, -0.96198777, -0.25573585],
        [-0.44544105, -0.21466774, -0.32679925,  0.15732642]],

       [[ 0.18690841,  1.6018296 ,  0.18874649, -0.13237342],
        [-0.8271466 , -0.05786792,  1.80411106, -0.06284444],
        [ 0.30918083, -0.35194786, -0.64168061, -0.57842455],
        [-0.61732766,  0.06326159, -0.96198777, -0.25573585],
        [-0.44544105, -0.21466774, -0.32679925,  0.15732642]],

       [[ 0.18690841,  1.6018296 ,  0.18874649, -0.13237342],
        [-0.8271466 , -0.05786792,  1.80411106, -0.06284444],
        [ 0.30918083, -0.35194786, -0.64168061, -0.57842455],
        [-0.61732766,  0.06326159, -0.96198777, -0.25573585],
        [-0.44544105, -0.21466774, -0.32679925,  0.15732642]],

       [[ 0.18690841,  1.6018296 ,  0.18874649, -0.13237342],
  

## Вывод результатов для нового массива нормального (Гауссового) распределения:

In [ ]:
data = np.random.normal(3, 2.5, size=(6, 4))
data

array([[ 4.40207443,  3.85060491,  3.94866161,  4.37561128],
       [ 0.63060583,  2.21489261,  5.65769944,  1.32942839],
       [ 0.51701621,  3.70308522,  5.10928911, -5.02923171],
       [ 4.43212552,  4.69361798,  3.43473673,  4.77991877],
       [ 2.78868158,  6.53850538,  4.27736972,  4.98914607],
       [ 4.64545718,  5.85633021,  5.19388097,  1.98574534]])

In [ ]:
Unar_Operations.floor(data, 2, 5, 1, 3)     # наибольшее целое число, не большее его при заданном срезе

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 3., 5., 0.],
       [0., 4., 3., 0.],
       [0., 6., 4., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Unar_Operations.floor(data)     # наибольшее целое число, не большее его для целого массива

array([[ 4.,  3.,  3.,  4.],
       [ 0.,  2.,  5.,  1.],
       [ 0.,  3.,  5., -6.],
       [ 4.,  4.,  3.,  4.],
       [ 2.,  6.,  4.,  4.],
       [ 4.,  5.,  5.,  1.]])

In [ ]:
Unar_Operations.sqrt(data, 2, 5, 1, 3)     # квадратный корень при заданном срезе

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.9243402 , 2.26037367, 0.        ],
       [0.        , 2.16647594, 1.85330427, 0.        ],
       [0.        , 2.55705013, 2.06818029, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [ ]:
Unar_Operations.sqrt(data)     # квадратный корень для целого массива

array([[2.09811211, 1.96229583, 1.98712395, 2.09179618],
       [0.79410694, 1.48825153, 2.3785919 , 1.15300841],
       [0.71903839, 1.9243402 , 2.26037367, 2.24259486],
       [2.10526139, 2.16647594, 1.85330427, 2.18630253],
       [1.6699346 , 2.55705013, 2.06818029, 2.23363965],
       [2.15533227, 2.41998558, 2.27900877, 1.40916477]])

In [ ]:
Unar_Operations.tanh(data, 2, 5, 1, 3)     # гиперболический тангенс при заданном срезе

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.99878575, 0.99992703, 0.        ],
       [0.        , 0.99983244, 0.99792411, 0.        ],
       [0.        , 0.99999581, 0.99961481, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [ ]:
Unar_Operations.tanh(data)     # гиперболический тангенс для целого массива

array([[ 0.99969983,  0.99909585,  0.9992568 ,  0.99968351],
       [ 0.55846923,  0.97644659,  0.99997563,  0.86910956],
       [ 0.47539384,  0.99878575,  0.99992703, -0.99991436],
       [ 0.99971733,  0.99983244,  0.99792411,  0.999859  ],
       [ 0.99246345,  0.99999581,  0.99961481,  0.99990721],
       [ 0.9998155 ,  0.99998362,  0.99993839,  0.96300651]])

## Вывод результатов для нового массива целых чисел:

In [ ]:
data = np.random.randint(10, size=(8, 9))
data

array([[4, 4, 1, 0, 6, 9, 8, 3, 4],
       [9, 7, 7, 4, 0, 8, 6, 3, 6],
       [7, 5, 3, 0, 6, 9, 2, 6, 4],
       [5, 9, 7, 3, 2, 1, 6, 4, 8],
       [7, 7, 3, 5, 9, 3, 9, 8, 2],
       [9, 4, 2, 4, 4, 0, 5, 9, 4],
       [2, 3, 0, 6, 1, 5, 7, 1, 8],
       [9, 1, 0, 7, 2, 7, 0, 4, 5]])

In [ ]:
Unar_Operations.square(data, 0, 8, 3, 6)     # возведение в квадрат при заданном срезе

array([[ 0.,  0.,  0.,  0., 36., 81.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 16.,  0., 64.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 36., 81.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  9.,  4.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 25., 81.,  9.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 16., 16.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 36.,  1., 25.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 49.,  4., 49.,  0.,  0.,  0.]])

In [ ]:
Unar_Operations.square(data)     # возведение в квадрат для целого массива

array([[16, 16,  1,  0, 36, 81, 64,  9, 16],
       [81, 49, 49, 16,  0, 64, 36,  9, 36],
       [49, 25,  9,  0, 36, 81,  4, 36, 16],
       [25, 81, 49,  9,  4,  1, 36, 16, 64],
       [49, 49,  9, 25, 81,  9, 81, 64,  4],
       [81, 16,  4, 16, 16,  0, 25, 81, 16],
       [ 4,  9,  0, 36,  1, 25, 49,  1, 64],
       [81,  1,  0, 49,  4, 49,  0, 16, 25]])

In [ ]:
Unar_Operations.isinf(data, 0, 8, 3, 6)     # булев массив, показывающий, какие элементы являются бесконечными при заданном срезе

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
Unar_Operations.isinf(data)     # булев массив, показывающий, какие элементы являются бесконечными для целого массива

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [ ]:
Unar_Operations.isfinite(data, 0, 8, 3, 6)     # булев массив, показывающий, какие элементы являются конечными (не inf и не NaN) при заданном срезе

array([[0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.]])

In [ ]:
Unar_Operations.isfinite(data)     # булев массив, показывающий, какие элементы являются конечными (не inf и не NaN) для целого массива

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
Unar_Operations.array_3d(data, 3)   # преобразование двухмерного массива в трехмерный массив

array([[[4, 4, 1, 0, 6, 9, 8, 3, 4],
        [9, 7, 7, 4, 0, 8, 6, 3, 6],
        [7, 5, 3, 0, 6, 9, 2, 6, 4],
        [5, 9, 7, 3, 2, 1, 6, 4, 8],
        [7, 7, 3, 5, 9, 3, 9, 8, 2],
        [9, 4, 2, 4, 4, 0, 5, 9, 4],
        [2, 3, 0, 6, 1, 5, 7, 1, 8],
        [9, 1, 0, 7, 2, 7, 0, 4, 5]],

       [[4, 4, 1, 0, 6, 9, 8, 3, 4],
        [9, 7, 7, 4, 0, 8, 6, 3, 6],
        [7, 5, 3, 0, 6, 9, 2, 6, 4],
        [5, 9, 7, 3, 2, 1, 6, 4, 8],
        [7, 7, 3, 5, 9, 3, 9, 8, 2],
        [9, 4, 2, 4, 4, 0, 5, 9, 4],
        [2, 3, 0, 6, 1, 5, 7, 1, 8],
        [9, 1, 0, 7, 2, 7, 0, 4, 5]],

       [[4, 4, 1, 0, 6, 9, 8, 3, 4],
        [9, 7, 7, 4, 0, 8, 6, 3, 6],
        [7, 5, 3, 0, 6, 9, 2, 6, 4],
        [5, 9, 7, 3, 2, 1, 6, 4, 8],
        [7, 7, 3, 5, 9, 3, 9, 8, 2],
        [9, 4, 2, 4, 4, 0, 5, 9, 4],
        [2, 3, 0, 6, 1, 5, 7, 1, 8],
        [9, 1, 0, 7, 2, 7, 0, 4, 5]]])